//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeFirst1108
{
    using System;
    using System.Collections.Generic;
    
    public partial class spt_fallback_dev
    {
        public string xserver_name { get; set; }
        public System.DateTime xdttm_ins { get; set; }
        public System.DateTime xdttm_last_ins_upd { get; set; }
        public Nullable<int> xfallback_low { get; set; }
        public string xfallback_drive { get; set; }
        public int low { get; set; }
        public int high { get; set; }
        public short status { get; set; }
        public string name { get; set; }
        public string phyname { get; set; }
    }
}
