//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BookInfo
    {
        public string BookID { get; set; }
        public string ISBN { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string BookVersion { get; set; }
        public Nullable<int> WordCount { get; set; }
        public Nullable<short> PageCount { get; set; }
        public string Publisher { get; set; }
        public string ClassID { get; set; }
    }
}
