//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _11._4代码先优作业
{
    using System;
    using System.Collections.Generic;
    
    public partial class dbo_Departnents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbo_Departnents()
        {
            this.dbo_Courses = new HashSet<dbo_Courses>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Dscn { get; set; }
        public string SortCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbo_Courses> dbo_Courses { get; set; }
        public virtual dbo_Departnents dbo_Departnents1 { get; set; }
        public virtual dbo_Departnents dbo_Departnents2 { get; set; }
    }
}
