//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demmo1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departmnt
    {
        public Departmnt()
        {
            this.Courses = new HashSet<Cours>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Dscn { get; set; }
        public string SortCode { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
    }
}
